import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}> {/* Apply font style */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
