// app/layout.js
import "./globals.css";
import Footer from '@/components/Footer';
import { Montserrat } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import LayoutWrapper from '@/components/LayoutWrapper'; 

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
});

export const metadata = {
  title: "Automated Candidate Screening",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <LayoutWrapper>{children}</LayoutWrapper>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
